### ISSUE TITLE
How would you go about making spline curves for the connecting lines?

### ISSUE THREAD

**Issue by PySimpleGUI** [derikvanschaik/MIMI#2]
I'm curious what your approach would be to get curved lines between the boxes.  I've not looked at the problem, but I've looked enviously at screenshots of network diagrams that have smooth, curved lines between the nodes.  Do you now how to go about doing something like that?

**Comment by derikvanschaik** [comment]
I am not really sure...I have thought about this before but couldn't come up with a method that makes the lines very crisp. Here is a solution I just drummed up although I am pretty sure you have thought of some variation of this method. Basically this attempts to make as close to infinitely many points as possible and connect them with lines. I do think it is possible to improve on this greatly, all I understand about the problem is you need very small points and a specific y to x scaling to make it look crisper.  
```python
import PySimpleGUI as sg
import numpy as np 

def draw_spline_curve(canvas, points):
    lastPoint = points[0]
    for point in points[1:]:
        # make the points smaller by using linspace
        xVals = np.linspace(lastPoint[0], point[0], num = 50 )
        yVals = np.linspace(lastPoint[1], point[1], num = 50 )   
        values = []
        # build up values array 
        for i in range(len(xVals)):
            values.append( (xVals[i], yVals[i]))

        lastSmallerPoint = values[0]
        for smallPoint in values:
            canvas.draw_line(lastSmallerPoint, smallPoint)
            lastSmallerPoint = smallPoint 
        # reassign last point to curpoint for next iteration 
        lastPoint = point

def main():
    canvas = sg.Graph((500, 500), (0,0), (500, 500), key='canvas',background_color='white')
    layout =[[canvas]] 
    window = sg.Window('tester', layout).finalize()
    draw_spline_curve(canvas, [(x + 250, (1/50)*(-x**(2)) + 500 ) for x in range(-500, 500)]) 

    while True: 
        event, values = window.read()
        if event == sg.WIN_CLOSED:
            break

    window.close() 
if __name__ == "__main__":
    main() 
```

**Comment by derikvanschaik** [comment]
@PySimpleGUI
I realize when looking at the code I can make a modification to make it a lot simpler and probably more efficient but it still does not solve the crispness issue
```python
import PySimpleGUI as sg
import numpy as np 

def draw_spline_curve(canvas, points):
    lastPoint = points[0] 
    for point in points[1:]:
        canvas.draw_line(lastPoint, point) 
        lastPoint = point

def main():
    canvas = sg.Graph((500, 500), (0,0), (500, 500), key='canvas',background_color='white')
    layout =[[canvas]] 
    window = sg.Window('tester', layout).finalize()
    draw_spline_curve(canvas, [(x + 250, (1/50)*(-x**(2)) + 500 ) for x in np.linspace(-500, 500, num = 50000)]) 

    while True: 
        event, values = window.read()
        if event == sg.WIN_CLOSED:
            break

    window.close() 
if __name__ == "__main__":
    main() 
```

**Comment by PySimpleGUI** [comment]
Oh wow!  That looks great!

![image](https://user-images.githubusercontent.com/46163555/142064499-ddef1388-25e7-4ff9-ae57-93e6bf987815.png)

I've not looked at this at all, so you're ahead of me on this one.  That was quick work!  I'm impressed.

**Comment by PySimpleGUI** [comment]
I don't know if it would be of help, but there's a multi-point draw:
![image](https://user-images.githubusercontent.com/46163555/142065135-726f277d-f5e1-4155-9433-990082f951a5.png)

You can pass it a list of points and it'll draw lines between each point.

**Comment by PySimpleGUI** [comment]
I get a similar look using this:

```python
import PySimpleGUI as sg
import numpy as np

def main():
    canvas = sg.Graph((500, 500), (0,0), (500, 500), key='canvas',background_color='white')
    layout =[[canvas]]
    window = sg.Window('tester', layout).finalize()
    
    points = [(x + 250, (1/50)*(-x**(2)) + 500 ) for x in np.linspace(-500, 500, num = 50000)]
    
    canvas.draw_polygon(points, fill_color='white', line_color='black' )


    while True:
        event, values = window.read()
        if event == sg.WIN_CLOSED:
            break

    window.close()
if __name__ == "__main__":
    main()
```

You know better than I do about these curves.  I just know the methods that are available 😀

**Comment by derikvanschaik** [comment]
@PySimpleGUI even better, never really looked into that method ever. I guess I gotta read the docs! Tinkering with the line_width property has given me a nicer result in this very specific example 
```python
import PySimpleGUI as sg
import numpy as np

def main():
    canvas = sg.Graph((500, 500), (0,0), (500, 500), key='canvas',background_color='white')
    layout =[[canvas]]
    window = sg.Window('tester', layout).finalize()
    # reduced step var 'num' 
    points = [(x + 250, (1/50)*(-x**(2)) + 500 ) for x in np.linspace(-500, 500, num = 100)] 
    # increase line_width argument 
    canvas.draw_polygon(points, fill_color='white', line_color='black', line_width=4)

    while True:
        event, values = window.read()
        if event == sg.WIN_CLOSED:
            break

    window.close()
if __name__ == "__main__":
    main()
```

**Comment by PySimpleGUI** [comment]
Oooo.....


![image](https://user-images.githubusercontent.com/46163555/142183659-dfb95a56-314f-458d-aca7-28efa446a25d.png)


Yeah, that's nice!

I've no clue how to go about using something like this to connect 2 rectangles like in a network diagram.

I think your line drawing version is likely superior though.  I'm not sure how to indicate (I've forgotten if it's even possible) that a "fill" should be transparent.  The `draw_polygon` will fill automatically.  I think your version is likely better in this situation.    I'll look at the tkinter method `create_polygon` to see what's possible.

Having a demo that's got diagrams like yours would be really great.  There so SO many applications for something that has boxes connected by lines.  These curved lines are the difference between a very very simple diagram and a professional-looking one.

It's through projects like yours and capabilities the Jason write and my own experimentation that builds the base of knowledge and makes it possible for more and more people to make bigger applications. 

One of the demos is a simple drawing application that shows how to click and move things around.  You too have shown others how to do a similar operation.  Now if someone wants to make a diagramming program, they'll have a nice jump-start.

--------------------------

## Speaking of Graph Elements....

While "poking around" yesterday to see a few things people built, I ran across this remarkable program that I wouldn't believe is a PySimpleGUI program.



# GrabCut-Annotation-Tool
https://user-images.githubusercontent.com/37477845/131681382-020df52c-dbc7-4750-80d1-42ff141ba829.mp4

Annotation tool using GrabCut() of OpenCV.<br>
It can be used to create datasets for semantic segmentation.<br>
\* Due to GrabCut's algorithm, it is suitable for annotation of data with clear boundaries.<br>

# Requirement 
* opencv-python 4.5.2.54 or later
* Pillow 7.2.0 or later
* PySimpleGUI 4.32.1 or later

# Directory
<pre>
│  app.py
│  config.json
│  
├─core
│  │  gui.py
│  └─util.py
│          
├─input
│      
└─output
    ├─image
    └─annotation
</pre>

#### app.py, core/gui.py, core/util.py
Source code.

#### input
Image files are stored in this directory.

#### output
Directory to save annotation results.
* image：The resized image is stored here
* annotation：Annotation result is stored her<br> * Saved in PNG format in palette mode

# Usage
Start it with the following command.
```
python app.py
```
The following options can be specified.
* --input<br>
Input image storage path<br>
Default：input
* --output_image<br>
Storage path of annotation result (image)<br>
Default：output/image
* --output_annotation<br>
Storage path of annotation result (segmentation image)<br>
Default：output/annotation
* --config<br>
Configuration file to be loaded<br>
Default：config.json

# Using GrabCut-Annotation-Tool
### File select
You can switch the annotation target by clicking the file list.<br>
keyboard shortcut 　↑、p：preview file　↓、n：next file<br>
<img src="https://user-images.githubusercontent.com/37477845/131686101-c94132bc-4b76-488a-85fe-69d9d9c216bd.png" width="80%">

### Initial ROI designation
You can specify the initial ROI by right-drag the mouse when "Select ROI" is displayed.<br>
<img src="https://user-images.githubusercontent.com/37477845/131687291-4f4c06d5-89fa-452d-925f-5576edc5af64.png" width="80%"><br><br>

After the drag is finished, GrabCut processing is performed.<br>
<img src="https://user-images.githubusercontent.com/37477845/131687690-295dc463-f82e-447b-86f8-65bbf6cf4e2d.png" width="80%"><br><br>

The area is selected.<br>
<img src="https://user-images.githubusercontent.com/37477845/131688127-3fc1c00e-0f99-435a-aa29-d9392c7af6d0.png" width="80%"><br><br>

### Background designation
You can specify the background by dragging the right mouse button.<br>
<img src="https://user-images.githubusercontent.com/37477845/131688309-c47184d9-f793-49f0-aa26-445ea2c2b431.png" width="80%"><br><br>

<img src="https://user-images.githubusercontent.com/37477845/131688599-dc78e307-8a3b-4ec7-a9be-05325486ee5e.png" width="80%"><br><br>

### 前景指定
You can switch to foreground specification by unchecking "Manually label background".<br>
keyboard shortcut　Ctrl<br>
<img src="https://user-images.githubusercontent.com/37477845/131688947-ab0505ca-8413-4afe-8d5a-c42ae1f25a3f.png" width="80%"><br><br>

You can specify the foreground by dragging the right mouse button.<br>
<img src="https://user-images.githubusercontent.com/37477845/131689310-5447308d-2019-48d7-8a43-df7707969599.png" width="80%"><br><br>

<img src="https://user-images.githubusercontent.com/37477845/131689509-ea0597a4-939a-4821-a077-40720687e8b1.png" width="80%"><br><br>

### Class ID switching
You can switch the class ID by pressing the check box.<br>
The single digit ID can be switched with a shortcut key.<br>
keyboard shortcut　0-9<br>
<img src="https://user-images.githubusercontent.com/37477845/131690009-862e763d-9714-4420-bf9c-7185daa0bbff.png" width="80%"><br><br>

After switching the class ID, it is necessary to specify the ROI.<br>
<img src="https://user-images.githubusercontent.com/37477845/131690463-667530d6-6e89-4eec-88ff-8a5aaf55a8a1.png" width="80%"><br><br>

<img src="https://user-images.githubusercontent.com/37477845/131690674-293340bc-eedb-48dc-9a20-8a5e4e61d1db.png" width="80%"><br><br>

### Auto save
Resized images and annotation images are automatically saved for each GrabCut process.<br>
<img src="https://user-images.githubusercontent.com/37477845/131691035-ab98cf83-f659-4efe-89aa-896badcee985.png" width="50%"><br><br>

If you do not want to save automatically, uncheck "Auto save".<br>
If you want to save other than auto save, press "s" on the keyboard.<br>
<img src="https://user-images.githubusercontent.com/37477845/131691394-72adf13c-c4dc-4df3-b1b2-f33d38acf226.png" width="80%"><br><br>

### Other settings
<img src="https://user-images.githubusercontent.com/37477845/131691853-0ce525ee-34dc-4328-9978-2ee8903a4d8e.png" width="80%"><br>
* Mask alpha：Image Mask Superimpose Display Shading Degree
* Iteration：Number of iterations of the GrabCut algorithm
* Draw thickness：Line thickness when foreground / background is specified
* Output width：Width of output image
* Output height：Vertical width of output image

# ToDo
- [x] ~~Memory leak improvement~~
- [x] ~~Allows other than upper left → lower right drag when ROI is selected~~
- [x] ~~Show ROI selection when class ID is selected with a shortcut key~~

# Author
Kazuhito Takahashi(https://twitter.com/KzhtTkhs)
 
# License 
GrabCut-Annotation-Tool is under [Apache-2.0 License](LICENSE).

The sample image uses the photograph of [フリー素材 ぱくたそ](https://www.pakutaso.com).

**Comment by derikvanschaik** [comment]
@PySimpleGUI The craziest part about this being implemented using the graph element is that I have literally no idea how they drew that image on the right using the available methods.....not even the slightest idea. I would never have even guessed this used the graph element to be honest. Also feel free to make a demo program that incorporates the textbox widgets I made, no problem! I would love to see that. I am pretty curious as to how this spline drawing could be used so I will probably start coding something up and see what works. If I come up with anything worth mentioning I will post it here!

**Comment by PySimpleGUI** [comment]
Please do lemme know if you end up adding something.  No pressure to do so, however.  I'm impressed you whipped up a little piece of sample code within a few hours of me asking about splines in general.  

![image](https://user-images.githubusercontent.com/46163555/142411194-62e206dd-62a7-457f-bde6-6edf84201a41.png)

It's been great chatting with you.  Thanks for taking a moment and working with me on this spline question.  Keep on making stuff!  You've got great instincts and can clearly work on problems quickly.
